/* Generated By:JavaCC: Do not edit this line. RiSCAssemblerTreeConstants.java Version 4.1d1 */
package parser;

public interface RiSCAssemblerTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTDIRECTIVE = 1;
  public int JJTCOMMAND = 2;
  public int JJTLABELDEC = 3;
  public int JJTLABEL = 4;
  public int JJTINSTRUCTION = 5;
  public int JJTPARAMETERS = 6;
  public int JJTARGUMENT = 7;
  public int JJTREGISTER = 8;
  public int JJTIMMEDIATE = 9;
  public int JJTMATCHEDBRACES = 10;
  public int JJTNOTPROCESS = 11;


  public String[] jjtNodeName = {
    "Input",
    "Directive",
    "Command",
    "LabelDec",
    "Label",
    "Instruction",
    "Parameters",
    "Argument",
    "Register",
    "Immediate",
    "MatchedBraces",
    "NotProcess",
  };
}
/* JavaCC - OriginalChecksum=bf5dfd0bb276d819b5b46216c03c40ba (do not edit this line) */
